name: Production deployment
on:
  push:
    branches:
      - master
env:
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"West Europe"'
  AZURE_WEBAPP_NAME: msgorgo-ttt-app

